### ISSUE TITLE
Intrinsic calculation math error for focal length in Y axis

### ISSUE THREAD

**Issue by mkrupczak3** [Theta-Limited/OpenAthenaIOS#27]
There's a Math error in the getIntrinsicMatrixFromKnownCCD:

```java
        double alpha_x = focalLength / mmWidthPerPixel; // focal length in pixel units
        alpha_x = alpha_x * scaleRatio; // scale down if image is scaled down
        double alpha_y = alpha_x / pixelAspectRatio; // focal length equivalent in pixel units, for the homogenous y axis in the image frame
        alpha_y = alpha_y * scaleRatio; // use the x-axis scale ratio because y axis is often cropped (and not EXIF tagged appropriately) and x axis usually isn't
```

Notice how alpha_y is multiplied by the scaleRatio twice! This makes the angle calculation for camera pitch offset to be skewed lower (absolute value) than it should be.

This is an error from my original code

Here is the fix, just delete the last line ` alpha_y = alpha_y * scaleRatio`:
https://github.com/Theta-Limited/OpenAthenaAndroid/commit/12875ef41ea678edb0836dbdfbe934e938de48fd

Line to delete in OpenAthenaIOS:
https://github.com/Theta-Limited/OpenAthenaIOS/blob/c642a9b253792492d77a0294ab1b6a2f78ab18f6/OpenAthenaIOS/DroneImage.swift#L974

We should probably get a hotfix out ASAP

**Comment by rdkgit** [comment]
Applied fix def improves accuracy!
