### ISSUE TITLE
Split up MGRS by GZD, square identifier, easting, and northing

### ISSUE THREAD

**Issue by rdkgit** [Theta-Limited/OpenAthenaIOS#40]
Aid in human readability.

**Comment by mkrupczak3** [comment]
Same as on Android:
https://github.com/Theta-Limited/OpenAthenaAndroid/issues/129

**Comment by mkrupczak3** [comment]
The mgrs-ios library we use allows these values to be extracted from an mgrsObject created from lat,lon.

The bindings for mgrsObject will likely be very similar to the java version of the library (see below for usage in OA Android):
https://github.com/Theta-Limited/OpenAthenaAndroid/blob/d88b455b9e7271688992290daeef63dcc64ff168/app/src/main/java/com/openathena/CoordTranslator.java#L53
