### ISSUE TITLE
DemCache searchCacheEntry prefer map with most local coverage rather than closest center

### ISSUE THREAD

**Issue by mkrupczak3** [Theta-Limited/OpenAthenaIOS#43]
Currently, the searchCacheEntry function for finding the best map with coverage of a seleted lat,lon returns the map with the closest centerpoint.

Given that the maps may be of variable diameter, the search function should instead return the map with the most local coverage in each direction around the search lat,lon. 

This change will ensure that for terrain-raycast, the map with the most coverage around the point will be used to reduce the incidence of ray Out Of Bounds errors:

Code change from the java app in https://github.com/Theta-Limited/OpenAthenaAndroid/commit/e93201885a3666b75eda88c8740204b164fd46f9
![Screenshot from 2024-05-03 15-21-53](https://github.com/Theta-Limited/OpenAthenaIOS/assets/25494111/823da9dc-a815-4cae-9735-d6b73bbf60a0)

**Comment by mkrupczak3** [comment]
The above code treats delta lat and delta lon as equivalent in terms of Euclidean distance. This isn't strictly true (Earth is an ellipsoid, not a sphere) but the approximation is good enough for the purposes of cache search

**Comment by rdkgit** [comment]
Fixed in next release of OAiOS
