### ISSUE TITLE
CoT circular error reported as negative for slant angles above horizon

### ISSUE THREAD

**Issue by mkrupczak3** [Theta-Limited/OpenAthenaIOS#47]
The trig formula for calculating expected circular error provides a negative value if the slant angle is above the horizon (a negative theta angle in OA notation)

The CursorOnTargetSender should use the absolute value as CE is a direction-agnostic measure:

See this commit with fix for OpenAthena-Android:
https://github.com/Theta-Limited/OpenAthenaAndroid/commit/555445a8e6989f9cd62ecff2d19db67b017f440c

**Comment by rdkgit** [comment]
Fixed by taking the fabs of value.
