### ISSUE TITLE
Correct for Lens Distortion using distortion parameters and Levenberg-Marquardt optimization

### ISSUE THREAD

**Issue by mkrupczak3** [Theta-Limited/OpenAthenaIOS#5]
I finally finished a fix for issue [74](https://github.com/Theta-Limited/OpenAthenaAndroid/issues/74) of the OpenAthenaAndroid project. 

After going back and forth with ChatGPT for many hours, I'm convinced that the implementation in the function [`getRayAnglesFromImgPixel()`]() of OpenAthenaAndroid is the best reasonable implementation for correcting for lens distortion.

Some background:
https://towardsdatascience.com/camera-intrinsic-matrix-with-example-in-python-d79bf2478c12?gi=af8d5e6f0e01
https://www.mathworks.com/help/vision/ug/camera-calibration.html#:~:text=The%20intrinsic%20parameters%20represent%20the,plane%20using%20the%20intrinsics%20parameters
https://support.pix4d.com/hc/en-us/articles/202559089-How-are-the-Internal-and-External-Camera-Parameters-defined
https://ieeexplore.ieee.org/document/5278053

The OpenAthenaAndroid engine uses the idealized pinhole camera mathematical model for modeling how light comes in through a camera lens and is digitized by a CMOS/CCD sensor. `perspective` lenses behave remarkably similar to this idealized mathematical model, however the properties of the lens itself may introduce certain radial and tangential distortion which causes the true ray angle of pixels in the image to deviate from what is expected by the idealized pinhole camera model.

The math for handling fisheye lenses is more complicated, and will likely need an different mathematical model in the future for true correctness.

Regarding `perspective` camera lenses which behave similarly to the pinhole camera model, one challenge with attempting to implement these distortion equations from the available literature is that these equations describe how an undistorted point becomes distorted, and not vice versa. The necessary reverse mapping of the one-way function thus becomes an optimization problem. I was originally looking at using [Newton's method](https://en.wikipedia.org/wiki/Newton%27s_method), however with the non-linearity of the problem this technique may produce incorrect results. 

The [Levenberg–Marquardt optimization algorithm](https://en.wikipedia.org/wiki/Levenberg%E2%80%93Marquardt_algorithm) is the optimization solver which seems to be more commonly used in computer vision applications. I used the Apache Commons Math library in Java which has a robust implementation of such an optimizer, but for iOS Swift you may need to find an implementation or code your own.

The function [`getRayAnglesFromImgPixel()`](https://github.com/Theta-Limited/OpenAthenaAndroid/blob/109beb474bc643ea0284f3d1c891f1e2995b9d01/app/src/main/java/com/openathena/MetadataExtractor.java#L699)  in `MetadataExtractor.java` contains most of the logic for setting up the Levenberg-Marquardt optimization problem. New classes [`FisheyeDistortionCorrection.java`](https://github.com/Theta-Limited/OpenAthenaAndroid/blob/master/app/src/main/java/com/openathena/FisheyeDistortionFunction.java) and [`PerspectiveDistortionCorrection.java`](https://github.com/Theta-Limited/OpenAthenaAndroid/blob/master/app/src/main/java/com/openathena/PerspectiveDistortionFunction.java) provide the optimization solver with both the distortion equations for the corresponding lens type and a Jacobian matrix which contains the first derivatives of these equations which may be useful to the optimization solver. 

Obviously this is a lot to go through, so you and I will likely need to work on this together. Finding or writing an Levenberg-Marquardt optimization solver for iOS Swift will be the most challenging aspect of an implementation.

**Comment by rdkgit** [comment]
Support added in LensDistortionCorrections feature branch.
