### ISSUE TITLE
Add warning message if camera intrinsics missing for drone model

### ISSUE THREAD

**Issue by mkrupczak3** [Theta-Limited/OpenAthenaIOS#60]
@rdkgit If camera intrinsics can't be found for the user's loaded drone image, a popup should appear which informs them calculations will be significantly less accurate than normal. 

It should also ask them to email support@theta.limited.

Here's what the popup looks like on Android:

<img src="https://github.com/user-attachments/assets/1d3415cb-329e-481b-8eb7-5dec761e27c6" alt="Screenshot_20240928-135132" width="256">

This change is important for maintaining the quality reputation of OpenAthena. If they load a drone image from a model not in our calibration database and get poor results, people could assume the software is broken or of poor quality.

**Comment by rdkgit** [comment]
Added popup if drone model not known after image loaded.  Fixed in 2.80
