### ISSUE TITLE
Handle make/model name collisions between some drone's color and thermal cameras.

### ISSUE THREAD

**Issue by mkrupczak3** [Theta-Limited/OpenAthenaIOS#7]
# Premise

Many commercial drones are now being sold which feature both a color optical camera and an infrared thermal camera. The thermal camera is especially useful for industrial settings and flights which occur at night.

A problem with our data processing for drone images however is that most multispectral DJI drones with both a color and thermal camera use the exact same make/model names for their thermal camera as they do their color camera. This may caused undefined behavior where a thermal image is mistakenly analyzed according to the intrinsics of the color camera (or vice versa).

To resolve these make/model name collisions, the OpenAthenaIOS metadata processor should find all objects from droneModels.json which match a specific make/model name. It should then use the `widthPixels` or `heightPixels` fields to select the camera with the number of pixels closest to the image itself. Given the novelty of thermal cameras and material challenges in their fabrication, we may safely assume that the color cameras will have much higher resolution than thermal for quite some time.

Another issue with processing thermal images is some drone models don't store focal length metadata in images taken by a thermal camera. Thankfully in these cases, the focal length of these cameras are fixed and invariant, and are known from commonly available technical documentaton. In cases where focalLength is not detected in image metadata, the OpenAthenaIOS metadata processor should look for the `focalLength` field in the drone JSON object. This field will only be present when the focal length is fixed and it is absolutely needed here for calculations.

# Reference implementation(s)

See the function [`getMatchingDrone()` in `MetadataExtractor.java`](https://github.com/Theta-Limited/OpenAthenaAndroid/blob/053734ee11f35240fc4092df60c9b83175b57016/app/src/main/java/com/openathena/MetadataExtractor.java#L117C30-L117C46) for an example of how the matching by image pixels should occur to resolve make/model name collisions between thermal and color cameras.

See this conditional in the function [`getIntrinsicMatrixFromKnownCCD()` in `MetadataExtractor.java`](https://github.com/Theta-Limited/OpenAthenaAndroid/blob/053734ee11f35240fc4092df60c9b83175b57016/app/src/main/java/com/openathena/MetadataExtractor.java#L593) for an example of how the OpenAthenaIOS metadata processor should attempt to find the `focalLength` field in a given drone's JSON object if focalLength information is not present in image EXIF/XMP metadata.

**Comment by rdkgit** [comment]
Fixed in DroneModelsUpdate feature branch.  Integrated into main.

**Comment by rdkgit** [comment]
Fixed in DroneModelsUpdate feature branch. Integrated into main.
