### ISSUE TITLE
Add multicast UDP "Cursor on Target" output from OpenAthenaIOS for compatibility with iTAK app

### ISSUE THREAD

**Issue by mkrupczak3** [Theta-Limited/OpenAthenaIOS#8]
# Premise

The [tak.gov](https://tak.gov/products) products are the definitive solution for operators in defense and public safety as the "interoperability of where" (location).

The products provide an appealing, highly-interoperable system which may share location information and situational awareness information quickly between and among operators on the ground. The system (with plugins) is also able to operate using radio modems over LAN even in situations where internet access is not available.

The backbone of the TAK protocol(s) is the Cursor On Target (commonly abbreviated CoT) message format. This message is an xml-like element tree which may define a type of object, its location, and the accuracy level of this information. Given its simplicity and portability, it is an appealing Marshalled data format which allows interoperability between wildly varying end devices and software.

OpenAthenaAndroid is designed to send a CoT UDP multicast message to udp://239.2.3.1:6969 (which is a multicast IP address), which is the default address on localhost ATAK is programed to receive CoT messages from. Once a CoT message is delivered to the user's local TAK app, it is trivial for them to relay it to other networked users using the TAK app interface.

For OpenAthenaIOS to reach parity with OpenAthenaAndroid, it should be able to send a CoT message to iTAK just as OpenAthenaAndroid may to ATAK. There may exist some challenges to such an implementation I may not be aware of, for example I do not know if iTAK is set to receive multicast UDP CoT messages or if iOS allows sending or receipt of such datagrams. 

# Reference implementation

A reference implementation for the CoT message sending functionality is available in the file [`CursorOnTargetSender.java` of OpenAthenaAndroid](https://github.com/Theta-Limited/OpenAthenaAndroid/blob/master/app/src/main/java/com/openathena/CursorOnTargetSender.java). [This GitHub issue](https://github.com/Theta-Limited/OpenAthenaAndroid/issues/15) I was using to track details related to this implementation contains links to a wealth of documentation around the CoT protocol. Specifically, the PDF document `Cursor-on-Target Message Router User’s Guide` from MITRE contains much useful information about the CoT message format, including the mandatory fields.

**Comment by rdkgit** [comment]
Feature now included in main branch via CursorOnTarget feature branch.
